# use lightweight Python 3.7 image.
# https://hub.docker.com/_python
FROM python:3.7-slim

#Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

#install production dependencies.
RUN pip install Flask gunicorn

#run the web service on container startup.here we use the gunicorn.
#web server ,with one worker process and 8 thered.
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 app:app